spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://82.157.167.106:3306/jiagousheji?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jiagou123